server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY:}